<?php
define("FITBIT_KEY", "XXXXXXXXXX");
define("FITBIT_SECRET", "XXXXXXXXXX");

define("TWITTER_KEY", "XXXXXXXXXX");
define("TWITTER_SECRET", "XXXXXXXXXX");

define("TWITTER_ACCESS_TOKEN", "XXXXXXXXXX");
define("TWITTER_ACCESS_TOKEN_SECRET", "XXXXXXXXXX");


